Messed with the workflow even more.

diff --git a/.github/workflows/npm-install.yml b/.github/workflows/npm-install.yml
--- a/.github/workflows/npm-install.yml
+++ b/.github/workflows/npm-install.yml
@@ -15,9 +15,17 @@ jobs:
 
       - name: Creating generate script
         run: touch generate.sh
-      - name: Appending content to script
+      - name: Appending content to script.
         run: echo "sudo npm i && sudo npm i -g docpad" >> generate.sh
-      - name: Appending more content to script
-        run: echo "docpad generate" >> generate.sh
+      - name: Appending more content to script.
+        run: echo "sudo docpad generate" >> generate.sh
+      - name: Even more appending!
+        run: echo "if [ $? -eq 0 ]; then" >> generate.sh
+      - name: Jeez, you're filling this file up.
+        run: echo "   echo Command passed successfully." >> generate.sh
+      - name: Okay, you can stop.
+        run: echo "else" >> generate.sh
+      - name: Final appendation.
+        run: echo "   echo Command failed." >> generate.sh
       - name: Executing script
         run: sh generate.sh
